### ISSUE TITLE
Issue with installing plugin on v1.2.13

### ISSUE THREAD

**Issue by SunnyR** [kernworks/OpenVBX-Plugin-Recording#5]
1. There is a unterminated comment in recording.php which begins at line 109
2. Also my error log shows Missing file in plugin: OpenVBX-Plugin-Recording-master :: config.php

Any solutions to the second issue?

**Comment by SunnyR** [comment]
Nvm the config.php file is when visting the settings page. However when i click on recorded calls on the left sidebar, i see this issue in the server log:
Maximum execution time of 30 seconds exceeded in public_html/calls/OpenVBX/libraries/Services/Twilio/TinyHttp.php on line 87

**Comment by kernworks** [comment]
That means you have a very large number of recordings associated to your Twilio account.

You can try adding: `set_time_limit (0);` to the second line of recording.php to see if this helps.
This will not work if PHP is running is safe mode. Also, this may cause some strain on your web server if too many users are looking at that page.

Please let us know if that helps. We are working on a method of pagination but it is very difficult due to the limitations of how recordings are presented to the Twilio API.

**Comment by SunnyR** [comment]
Yeah that does seem to work, the results dont show since the list is too long and takes forever the page to load. However if i interrupt it i can see the results in unstyled html format.

I will look into pagination myself as well, and if i can get it done by tomorrow i will post it here for you

**Comment by SunnyR** [comment]
I didnt get much time to work on it yet, so for now i simply break out of the loop after 20 iterations of the foreach loop. So its all working for now.

**Comment by kernworks** [comment]
@AvengersArmy , take a look at the feature-max-execution branch: https://github.com/kernworks/OpenVBX-Plugin-Recording/tree/feature-max-execution

This is a different approach than what you are doing currently. Instead of breaking after 20 loops, it will try to show as many recordings as possible within the max execution timeout for PHP.

**Comment by chetantrivedi7** [comment]
Hi ,
i have faced issue with your recording plugin in openvbx 1.20 latest version .its not display all recorded call .I have seen only 1 to 2 recorded call in list .please help me for short out this problem .

Thanks

**Comment by chetantrivedi7** [comment]
its take too much time for loading list and I have installed OpenVBX-Plugin-Recording-feature-max-execution plugin
